### ISSUE TITLE
Support utf8 nickname

### ISSUE THREAD

**Issue by Vlambeerg** [ckbaudio/valheim-discord-bot#1]
Need to add utf8 conversion when opening log file

```Python
while not bot.is_closed():
    with open(file,encoding='utf8') as f:
```

**Comment by ckbaudio** [comment]
> Need to add utf8 conversion when opening log file
> 
> ```python
> while not bot.is_closed():
>     with open(file,encoding='utf8') as f:
> ```

Thanks, should be sorted now :)
