### ISSUE TITLE
My deaths counter doesn't work

### ISSUE THREAD

**Issue by Lumiahna** [ckbaudio/valheim-discord-bot#2]
Hello,
I'm running valheim with lgsm, I enable logs with log files (Modified common,cfg to add -logfile /some/where/log.txt )but when I die, it doesn't seem the script detects it (It doesn't add +1 on death.csv).
Everything is ok on my config.py and runs well, only the deaths detection doesn't work.

**Comment by ckbaudio** [comment]
> Hello,
> I'm running valheim with lgsm, I enable logs with log files (Modified common,cfg to add -logfile /some/where/log.txt )but when I die, it doesn't seem the script detects it (It doesn't add +1 on death.csv).
> Everything is ok on my config.py and runs well, only the deaths detection doesn't work.

Hi there. I'm not familiar with LGSM but by quickly looking at it, there are a variety of different logs that LGSM can produce. I'm not sure which is the right one, if it exists. I am using the core game engine log, which LGSM may have reformatted or may not exist. If you can specify launch options directly with the `/.valheim_server.x86_64` executable then add `./valheim_server.x86_64 -logfile /loc/of/log.txt` and use that location in `config.py`.  You can also use `grep '0:0' a_log_file.txt` in your shell, your output should look something like [this](https://i.imgur.com/z0VUeuQ.png). If you don't have any output, then you don't have the right log file. 

I've also added utf8 encoding recently so it would be advisable to download the latest version.

**Comment by Bazimek** [comment]
For me it is working fine. It worked fine with LGSM .log file, but I am using now the -logfile

**Comment by Lumiahna** [comment]
Hello,
well it worked with a little delay(+8hours), but without reason it's was "on real time" this morning.
I didn't kill or reboot anything, so I guess it's fixed.
Thanks for your support (And Indead, the -logfile /path/to/log.txt is mandatory)
