### ISSUE TITLE
A2S no response - ideas?

### ISSUE THREAD

**Issue by jphenow** [ckbaudio/valheim-discord-bot#5]
I keep getting `No reply from A2S, retrying` - any ideas to debug or anything? `lsof -i` shows my 2457 is indeed being listened to by valheim server. Checked firewalls etc. 

Cheers, thanks for writing - just curious if I'm missing something obvious.

**Comment by stolenvw** [comment]
does this site show your server as online?

https://geekstrom.de/valheim/check/

**Comment by stolenvw** [comment]
Also if you use `-public 0` A2S wont work

**Comment by jphenow** [comment]
Oho it's not public that's it 🤦 thanks a bunch!
